config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'

  resources :cooks, only: :index

  namespace :cook_dashboard do
    resources :cooks, only: %i[show update]
    resources :orders, only: %i[index update] do
      patch 'accept'
      patch 'decline'
      patch 'cancel'
    end
    resources :categories, except: %i[show edit]
  end

  resources :meals, only: %i[update new create destroy] do
    get 'details'
  end

  resources :baskets, only: :show do
    get 'create', on: :collection
    get 'total_price', on: :member
    resources :orders, only: :create
    resources :cooks, only: :show
    resources :meals, only: [] do
      get 'presence_checking'
    end
  end

  resources :users, only: :show do
    resources :orders, only: :index do
      patch 'accept'
    end
    patch 'update_details'
  end

  resources :basket_suborders, only: %i[create update destroy]
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_suborders
  has_many :meals, through: :basket_suborders

  def formatted_total_price
    total_price = 0.0
    basket_suborders.each do |suborder|
      total_price += suborder.total_price
    end

    formatted(total_price)
  end

  private

  def formatted(price)
    ('%.2f' % price).gsub('.', ',')
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!, except: %I[create the_meal_in_the_basket? total_price]

  def show
    @basket = Basket.find(params[:id])
    @user   = current_user
    @cook   = @basket.meals.first.category.cook
    @order  = Order.new
  end

  def create
    basket = Basket.create
    render json: basket.to_json
  end

  def total_price
    total_price = Basket.find(params[:id]).formatted_total_price
    render json: total_price.to_json
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/show.html.erb
<div class='orange-banner'>
  <div class='dashboard-container banner-title'>
    <h2>Chez Juju !</h2>
  </div>
</div>

<div class='dashboard-container page-lifted'>

  <!-- #1 ADRESSE DE LA PRESTATION -->

  <div class='dashboard-card mt-0'>
    <div class='dashboard-card-header flex-row-start-center'>
      <h3 class='dashboard-card-title'>#1 Adresse de la prestation</h3>
    </div>
    <div class='dashboard-card-body basket-form'>

      <%= simple_form_for @user, url: user_update_details_path(@user), method: 'PATCH' do |f| %>
        <%= f.error_notification %>
        <div class='row'>
          <div class='col-6'>
            <%= f.input :flat_number, label: "Etage et numéro d'appartement", placeholder: 'ex : Appartement n°12',
                input_html: { class: 'details-form-item static-form-item flex-row-start-center inactive-input' } %>
          </div>
          <div class='col-6'>
            <%= f.input :digicode, label: 'Digicode', placeholder: 'ex : B123',
                input_html: { class: 'details-form-item static-form-item flex-row-start-center inactive-input' } %>
          </div>
        </div>
        <%= f.input :address, label: 'Adresse', placeholder: 'ex : 100 rue de Rivoli',
            input_html: { class: 'details-form-item static-form-item flex-row-start-center inactive-input' } %>
        <div class='row'>
          <div class='col-6'>
            <%= f.input :city, label: 'Ville', placeholder: 'ex : Paris',
                input_html: { class: 'details-form-item static-form-item flex-row-start-center inactive-input' } %>
          </div>
          <div class='col-6'>
            <%= f.input :zip, label: 'Code Postal', placeholder: 'ex : 75001',
                input_html: { class: 'details-form-item static-form-item flex-row-start-center inactive-input' } %>
          </div>
        </div>
        <%= f.input :phone_number, label: 'Numéro de téléphone', placeholder: 'ex : +33 6 12 34 56 78',
            input_html: { class: 'details-form-item static-form-item flex-row-start-center inactive-input' } %>
        <%= f.button :submit, id: 'edit-details-btn', class: 'red-btn-xl light-red-btn', value: 'Modifier les informations', data: { disable_with: false } %>
        <%= f.button :submit, id: 'update-details-btn', class: 'red-btn-xl hidden', value: 'Enregistrer les informations', data: { disable_with: false } %>
      <% end %>

    </div>
  </div>

  <!-- #2 PAYEMENT DE LA COMMANDE -->

  <div class='dashboard-card'>
    <div class='dashboard-card-header flex-row-start-center'>
      <h3 class='dashboard-card-title'>#2 Finalisation de la commande</h3>
    </div>
    <div class='dashboard-card-body basket-form'>

      <%= simple_form_for @order, url: basket_orders_path(@basket), method: 'POST' do |f| %>
        <%= f.input :instructions, as: :text, label: 'Avez-vous des instructions spécifiques pour votre cuisinier ?', placeholder: 'ex : ...',
            input_html: { rows: 5, class: 'details-form-item static-form-item flex-row-start-center' } %>

        <h3>Réglement de la commande</h3>
        <div class='flex-row-sb-center my-3'>
          <h4>Total 15,70€</h4>
          <h4 class='orange-14 underline pointer'>Voir le panier</h4>
        </div>

        <div class='payement-area flex-row-center-center'>
          <p>Une fois la commande confirmée, celle-ci doit être validée par le cuisinier.
          C’est seulement cette étape franchie que la procédure de payement vous sera transmis.</p>
        </div>

        <%= f.input :cgu_validation, label: "J'ai bien pris connaissance des CGU... bla-bla-bla"  %>

        <%= f.button :submit, id: '', class: 'red-btn-xl', value: 'Valider ma commande', data: { disable_with: false } %>
      <% end %>

    </div>
  </div>

</div>


  <%= javascript_pack_tag 'basketShow'%>