config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'

  resources :cooks, only: :index

  namespace :cook_dashboard do
    resources :cooks, only: %i[show update]
    resources :orders, only: %i[index update] do
      patch 'accept'
      patch 'decline'
      patch 'cancel'
    end
    resources :categories, except: %i[show edit]
  end

  resources :meals, only: %i[update new create destroy] do
    get 'details'
  end

  resources :baskets, only: :show do
    get 'create', on: :collection
    get 'total_price', on: :member
    resources :orders, only: :create
    resources :cooks, only: :show
    resources :meals, only: [] do
      get 'presence_checking'
    end
  end

  resources :users, only: :show do
    resources :orders, only: :index do
      patch 'accept'
    end
    patch 'update_details'
  end

  resources :basket_suborders, only: %i[create update destroy]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cook
  belongs_to :customer, class_name: 'User'
  has_many   :suborders
end

app/controllers/cook_dashboard/categories_controller.rb
class CookDashboard::CategoriesController < ApplicationController
  include UpdateRanksConcern

  def index
    @user = current_user
    @cook = @user.cook
    @categories = @cook.categories.order(:rank)
  end

  def new
    @category = Category.new
    @cook = current_user.cook
  end

  def create
    category = Category.new
    category.rank = current_user.cook.categories.count + 1
    save_category_based_on_params(category)
  end

  def update
    category = Category.find(params[:id])
    save_category_based_on_params(category)
  end

  def destroy
    category = Category.find(params[:id])
    cook = current_user.cook
    update_ranks(category, # selected_element
                 cook.categories.count, # new_rank
                 category.rank) # old_rank
    category.destroy
    redirect_to cook_dashboard_categories_path
  end

  private

  def save_category_based_on_params(category)
    cook = current_user.cook
    required_params = params.require(:category).permit(:name, :rank)
    category.update(name: required_params[:name], cook: cook)
    update_ranks(category, # selected_element
                 required_params[:rank].to_i, # new_rank
                 category.rank) # old_rank
    redirect_to cook_dashboard_categories_path
  end
end

app/controllers/cook_dashboard/cooks_controller.rb
class CookDashboard::CooksController < ApplicationController
  def show
    @user = current_user
    @cook = current_user.cook
  end

  def update
    cook_details = params.require(:cook).permit(:first_name, :last_name, :description)
    current_user.cook.update(cook_details)
    redirect_back(fallback_location: homepage_path)
  end
end

app/controllers/cook_dashboard/orders_controller.rb
class CookDashboard::OrdersController < ApplicationController
  def index
    @user = current_user
    @order = Order.last
  end

  def update
    # something
    update_customer_validation(nil)
  end

  def accept
    update_cook_validation(true)
  end

  def decline
    update_cook_validation(false)
  end

  def cancel
    update_cook_validation(nil)
  end

  private

  def update_cook_validation(new_status)
    @order = Order.find(params[:order_id])
    @order.cook_validation = new_status
    @order.save
    redirect_to cook_dashboard_orders_path
  end

  def update_customer_validation(new_status)
    @order = Order.find(params[:order_id])
    @order.customer_validation = new_status
    @order.save
    redirect_to cook_dashboard_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @user = current_user
    @order = Order.last
  end

  def create
    order_details = params.require(:order).permit(:instructions, :cgu_validation)
    basket = Basket.find(params[:basket_id])
    cook = basket.meals.first.category.cook
    order = Order.new(cook: cook,
                      customer_id: current_user.id,
                      instructions: order_details[:instructions],
                      cgu_validation: order_details[:cgu_validation],
                      customer_validation: true,
                      status: 'En attente de validation...')

    redirect_to homepage_path unless order.save

    basket.basket_suborders.each do |basket_suborder|
      suborder = Suborder.new(meal: basket_suborder.meal,
                              quantity: basket_suborder.quantity,
                              order: order)
      redirect_to homepage_path unless suborder.save
    end

    redirect_to user_orders_path(current_user)
  end

  def accept
    @order = Order.find(params[:order_id])
    @order.customer_validation = true
    @order.save
    redirect_to user_orders_path(current_user)
  end
end

app/helpers/cook_dashboard/categories_helper.rb
module CookDashboard::CategoriesHelper
end

app/helpers/cook_dashboard/cooks_helper.rb
module CookDashboard::CooksHelper
end

app/helpers/cook_dashboard/orders_helper.rb
module CookDashboard::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cook_dashboard/orders/index.html.erb
<div class='yellow-banner'>
  <div class='dashboard-container banner-title'>
    <h2>Mes missions</h2>
  </div>
</div>

<div class='dashboard-container page-lifted'>

  <!-- DÉTAILS PART -->


  <div class='dashboard-card mt-0'>
    <div class='dashboard-card-header flex-row-sb-center'>
      <h3 class='dashboard-card-title'>Jeudi 3 Mars  2020</h3>
      <h3 class='dashboard-card-title'>Popote n°253681</h3>
    </div>
    <div class='dashboard-card-body'>

      <div class='flex-row-sb-center mb-2 w-100 px-3'>
        <div>
          <p class='mb-2'>Commandée par Clara Dupuis</p>
          <p>À partir de 18h jusqu’à 19h30</p>
        </div>
        <div class='small-btn'>Contacter</div>
      </div>

      <% @order.suborders.each do |suborder| %>
        <div class='row my-3 p-0'>
          <div class='col-3 pl-0 flex-column-center-center'>
            <div class='flex-column-center-center'>
              <div class='flex-row-sb-center mb-2'>
                <div class='minus-btn pointer very-light-grey-14'><i class="fas fa-minus-circle"></i></div>
                <p class='flex-row-center grey-16 suborder-quantity'><%= suborder.quantity %>x</p>
                <div class='plus-btn pointer very-light-grey-14'><i class="fas fa-plus-circle"></i></div>
              </div>
              <div class='flex-column-center-center pt-2'>
                <p class='subtotal mb-2'>Sous-total</p>
                <p class='grey-16'>15,70€</p>
              </div>
            </div>
          </div>
          <div data-id='<%= suborder.meal.id %>'  class='col-9 meal-card white-card-border flex-row-sb-center'>
            <%= render partial: 'shared/meal_card_content', locals: {meal: suborder.meal} %>
          </div>
        </div>
      <% end %>

      <div class='flex-row-sb-center my-3 px-3'>

        <div class='flex-column-sb'>
          <h3 class='mb-2'>Total</h3>
          <p class='grey-16'>15,70€</p>
        </div>

        <% if @order.cook_validation == nil %>
          <div class='flex-column-sb'>
            <%= link_to cook_dashboard_order_accept_path(@order), method: 'PATCH' do %>
              <div class='small-btn green-bg-small-btn mb-2'>Valider</div>
            <% end %>
            <%= link_to cook_dashboard_order_decline_path(@order), method: 'PATCH' do %>
              <div class='small-btn orange-border-small-btn'>Décliner</div>
            <% end %>
          </div>
        <% end %>


        <% if @order.customer_validation == true && @order.cook_validation == true %>
          <div class='flex-column-center-center'>
            <h3 class='green-font mb-2'>Validée !</h3>
            <%= link_to cook_dashboard_order_cancel_path(@order), method: 'PATCH' do %>
              <div class='small-btn'>Annuler</div>
            <% end %>
          </div>
        <% end %>

        <% if @order.cook_validation == false %>
          <div class='flex-column-center-center'>
            <h3 class='orange-font mb-2'>Déclinée</h3>
            <%= link_to cook_dashboard_order_cancel_path(@order), method: 'PATCH' do %>
              <div class='small-btn'>Annuler</div>
            <% end %>
          </div>
        <% end %>

        <% if @order.customer_validation == nil && @order.cook_validation == true %>
          <div class='flex-column-sb'>
            <h3 class='mb-2'>En attente de validation...</h3>
            <%= link_to cook_dashboard_order_decline_path(@order), method: 'PATCH' do %>
              <div class='small-btn orange-border-small-btn'>Décliner</div>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>
  </div>

</div>