config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'

  resources :cooks, only: :index

  namespace :cook_dashboard do
    resources :cooks, only: %i[show update]
    resources :orders, only: %i[index update] do
      patch 'accept'
      patch 'decline'
      patch 'cancel'
    end
    resources :categories, except: %i[show edit]
  end

  resources :meals, only: %i[update new create destroy] do
    get 'details'
  end

  resources :baskets, only: :show do
    get 'create', on: :collection
    get 'total_price', on: :member
    resources :orders, only: :create
    resources :cooks, only: :show
    resources :meals, only: [] do
      get 'presence_checking'
    end
  end

  resources :users, only: :show do
    resources :orders, only: :index do
      patch 'accept'
    end
    patch 'update_details'
  end

  resources :basket_suborders, only: %i[create update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_suborders
  has_many :meals, through: :basket_suborders

  def formatted_total_price
    total_price = 0.0
    basket_suborders.each do |suborder|
      total_price += suborder.total_price
    end

    formatted(total_price)
  end

  private

  def formatted(price)
    ('%.2f' % price).gsub('.', ',')
  end
end

app/models/basket_suborder.rb
class BasketSuborder < ApplicationRecord
  belongs_to :meal
  belongs_to :basket

  def total_price
    quantity * meal.price
  end

  def formatted_total_price
    formatted(total_price)
  end

  private

  def formatted(price)
    ('%.2f' % price).gsub('.', ',')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :cook
  has_many   :meals

  include ChildrenRanksConcern
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :user
  has_many   :categories
  has_many   :orders
  has_many   :meals

  include ChildrenRanksConcern
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_one_attached :photo

  belongs_to :category, optional: true
  belongs_to :cook
  has_many   :basket_suborders
  has_many   :suborders
  has_many   :ingredients

  include ChildrenRanksConcern

  def formatted_price
    puts id
    formatted(price)
  end

  private

  def formatted(price)
    ('%.2f' % price).gsub('.', ',')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cook
  belongs_to :customer, class_name: 'User'
  has_many   :suborders
end

app/models/suborder.rb
class Suborder < ApplicationRecord
  belongs_to :meal
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cook
  has_many :orders, foreign_key: :customer_id

  validates :first_name, presence: true
  validates :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  def index
    @cooks = Cook.all
  end

  def show
    @cook = Cook.find(params[:id])
    @categories = @cook.categories
    @basket = Basket.find(params[:basket_id])
    @suborders = @basket.basket_suborders
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  include UpdateRanksConcern

  def details
    meal = Meal.find(params[:meal_id])
    render json: meal.to_json
  end

  def presence_checking
    basket = Basket.find(params[:basket_id])
    meal   = Meal.find(params[:meal_id])
    if basket.meals.include?(meal)
      render json: BasketSuborder.where(meal: meal, basket: basket).first.id.to_json
    else
      render json: 0.to_json
    end
  end

  def new
    @meal = Meal.new
    @categories = current_user.cook.categories.order(created_at: :desc)
  end

  def create
    meal = Meal.new
    save_meal_based_on_params(meal)
    redirect_to cook_dashboard_categories_path
  end

  def update
    meal = Meal.find(params[:id])
    save_meal_based_on_params(meal)
    redirect_back(fallback_location: homepage_path)
  end

  def destroy
    meal = Meal.find(params[:id])
    update_ranks(meal, # selected_element
                 meal.category.meals.count, # new_rank
                 meal.rank) # old_rank
    if meal.suborders.empty? && meal.basket_suborders.empty?
      meal.destroy
    else
      meal.deleted = true
      meal.save
    end
    redirect_to cook_dashboard_categories_path
  end

  private

  def save_meal_based_on_params(meal)
    meal.update(params.require(:meal).permit(:photo))
    required_params = params.require(:meal).permit(:name, :information, :description, :price, :category_id, :rank, :photo)
    meal.name        = required_params[:name]
    meal.information = required_params[:information]
    meal.description = required_params[:description]
    meal.price       = required_params[:price].gsub(',', '.').to_f
    meal.category_id = required_params[:category_id]
    meal.cook        = current_user.cook

    unless required_params[:rank].nil?
      meal.rank = required_params[:rank]
    else
      meal.rank = Category.find(required_params[:category_id]).meals.count + 1
    end

    meal.save

    update_ranks(meal, # selected_element
                 required_params[:rank].to_i, # new_rank
                 meal.rank) # old_rank

    meal.ingredients.each { |ingredient| ingredient.destroy }

    if params[:meal].keys.include?('ingredients')
      ingredients = params.require(:meal).require(:ingredients).permit!
      ingredients = ingredients.to_h.sort_by { |_, value| value['rank'] }
      ingredients.each_with_index do |item, index|
        name = item[1]['name']
        unless name.empty?
          ingredient = Ingredient.new(meal: meal, rank: index + 1, name: name)
          ingredient.save
        end
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <script src="https://kit.fontawesome.com/04806abca7.js" crossorigin="anonymous"></script>

    <title>Popote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body
    <% if (params[:controller] == 'users' && params[:action] == 'show') ||
          (params[:controller] == 'baskets' && params[:action] == 'show') ||
          (params[:controller] == 'orders' && params[:action] == 'index') ||
          (params[:controller] == 'cook_dashboard/orders' && params[:action] == 'index') ||
          (params[:controller] == 'cook_dashboard/categories' && params[:action] == 'index') ||
          (params[:controller] == 'cook_dashboard/categories' && params[:action] == 'new') ||
          (params[:controller] == 'cook_dashboard/cooks' && params[:action] == 'show') ||
          (params[:controller] == 'meals' && params[:action] == 'new') %>
      class='beige-bg'
    <% end %>
  >

    <%= render 'shared/navbar' %>
    <%= render 'shared/navbar_menu' %>
    <%= yield %>
    <%= render 'shared/flashes' %>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
  </body>
</html>

<%= javascript_pack_tag 'navbar'%>

app/views/shared/_category_form.html.erb
<%= simple_form_for category, url: url, method: method do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: 'Nom de la catégorie', placeholder: 'ex : ...',
      input_html: { class: 'details-form-item static-form-item flex-row-start-center' } %>
  <%= f.input :rank, collection: category_ranks,
                     label: 'Rang',
                     selected: category.rank.nil? ? category_ranks.last : category_ranks[category.rank-1],
                     include_blank: false,
                     input_html: { class: 'details-form-item static-form-item flex-row-start-center',
                     value: category.rank } %>
  <%= f.button :submit, id: 'update-details-btn', class: 'red-btn-xl', value: button, data: { disable_with: false } %>
<% end %>

app/views/shared/_cook_card.html.erb
  <div data-cook_id='<%= cook.id %>' class='white-card-shadow cook-card' >
    <%= image_tag 'cook.jpg', class: 'cook-card-image' %>
    <div class='cook-card-mark white-card-shadow flex-row-center-center'>
      <i class="fas fa-star yellow-font star"></i>
      <p class='yellow-font'>4.5 Très bien</p>
    </div>
    <div class='cook-card-content flex-column-sb'>
      <h3><%= cook.user.first_name %></h3>
      <p>Américain • Poulet • Poulet Frit • Salade • Sandwiches • Burgers</p>
      <ul class='cook-card-list orange-14'>
        <li>Un peu d’Asie dans le logis</li>
        <li>Voyage vegan oriental</li>
        <li>Que du gras</li>
      </ul>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_meal_card_content.html.erb
<div class='flex-column-sb h-100'>
  <h3><%= meal.name %></h3>
  <p>Hommos, moutabal, tabouleh, assortiments de beignets...</p>
  <p class='grey-16'><%= meal.formatted_price %> €</p>
</div>
<%= image_tag 'meal.jpg', class: 'meal-card-image' %>

app/views/shared/_meal_form.html.erb
<%= simple_form_for meal, url: url, method: method do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: 'Nom de la recette', placeholder: 'ex : Hamburger',
      input_html: { class: 'details-form-item static-form-item flex-row-start-center' } %>
  <%= f.input :photo, as: :file %>
  <% if meal.photo.attached? %>
    <%= cl_image_tag meal.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>

  <!-- DÉBUT DE LA PARTIE INGRÉDIENTS -->

  <label>Ingrédients</label>
  <div class='ingredients-area'>
    <%= f.simple_fields_for :ingredients do |h| %>
      <div class='wrapper-ingredients'>
        <% meal.ingredients.each do |ingredient| %>
          <%= h.simple_fields_for ingredient.rank.to_s.to_sym do |k|  %>
            <div class='wrapper-item-ingredient row'>
              <div class='col-2 p-0 grey-16  flex-row-center-center'>
                <%= k.input :rank, collection: ingredient_ranks, label: false, selected: ingredient_ranks[ingredient.rank-1], include_blank: false,
                    input_html: { class: 'p-0 details-form-item ingredient-qtt grey-14 flex-row-end-center', value: ingredient.rank } %>
              </div>
              <div class='p-0 col-8'>
                <%= k.input :name, label: false, placeholder: 'ex : Tomate',
                    input_html: { class: 'details-form-item static-form-item flex-row-start-center', value: ingredient.name } %>
              </div>
              <div class='pb-3 px-0 col-2 grey-16 pointer flex-row-center-center'>
                <div class='delete-ingredient-item'><i class="fas fa-times"></i></div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <p class='add-ingredient-item orange-14 pointer underline mb-3'>Ajouter un ingrédient</p>
  </div>

  <!-- FIN DE LA PARTIE INGRÉDIENTS -->

  <%= f.input :description, as: :text, label: 'Description', placeholder: 'ex : ...',
      input_html: { rows: 5, class: 'details-form-item static-form-item flex-row-start-center' } %>
  <%= f.input :information, as: :text, label: 'Informations supplémentaires', placeholder: 'ex : ...',
      input_html: { rows: 5, class: 'details-form-item static-form-item flex-row-start-center' } %>
  <%= f.input :price, label: 'Prix par portion en €', placeholder: 'ex: 10,00€',
      input_html: { class: 'details-form-item static-form-item flex-row-start-center' } %>
  <% unless url == meals_path && method == 'POST' %>
    <%= f.input :rank, collection: meal_ranks,
                       label: 'Rang',
                       selected: meal.rank.nil? ? meal_ranks.last : meal_ranks[meal.rank-1],
                       include_blank: false,
                       input_html: { class: 'details-form-item static-form-item flex-row-start-center',
                       value: meal.rank } %>
  <% end %>
  <%= f.association :category, collection: categories, label: 'Collection', placeholder: 'Téléphone', include_blank: false,
      input_html: { class: 'details-form-item static-form-item flex-row-start-center' } %>
  <%= f.button :submit, id: 'update-details-btn', class: 'red-btn-xl', value: button, data: { disable_with: false } %>
<% end %>

app/views/shared/_meal_pop_up.html.erb
<div id='meal-pop-up' data-id='' data-price='' class='meal_pop_up_bg_filter hidden'>
  <div class='meal_pop_up_card white-card'>
    <div class='meal_pop_up_header flex-row-center-center'>
      <h3 id='meal-pop-up-name'>Hachis parmentier</h3>
      <div id='meal_pop_up_cross' class='quit-meal-pop-up grey-16'><i class="fas fa-times"></i></div>
    </div>
    <div class='meal_pop_up_content'>
    </div>
    <div class='meal_pop_up_footer flex-row-sb-center'>
      <div class='white-btn mr-2'>

        <div class='flex-row-center-center'>
          <div id='meal-pop-up-minus-btn' class='very-light-grey-14 pointer'><i class="fas fa-minus-circle"></i></div>
          <p id='meal-pop-up-quantity' class='grey-16 basket-order-number flex-row-center-center'>1</p>
          <div id='meal-pop-up-plus-btn' class='very-light-grey-14 pointer'><i class="fas fa-plus-circle"></i></div>
        </div>

      </div>
      <div id='meal-pop-up-total-btn' class='quit-meal-pop-up red-btn'>Total 16,00 €</div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class='white-bg sticky-top'>
  <div class="navbar navbar-expand-md navbar-light navbar-lewagon">

    <%= link_to homepage_path, class: "" do %>
      <%= image_tag 'logo.png', class: 'navbar-logo' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <% if signed_in? && current_user.admin? %>
          <li class="nav-item active mt-10px mt-md-0">
            <%= link_to "Espace Administrateur", "#", class: "orange-16 mr-4 dashboard-btn flex-row-center-center nav-link" %>
          </li>
        <% end %>

        <% if !signed_in? || (signed_in? && current_user.cook.nil?) %>
          <li class="nav-item active mt-10px mt-md-0">
            <%= link_to "Devenez cuisinier !", "#", class: "orange-16 mr-4 underline nav-link" %>
          </li>
        <% else %>
          <li class="nav-item active mt-10px mt-md-0">
            <%= link_to "Espace Cuisinier", "#", class: "orange-16 mr-4 dashboard-btn flex-row-center-center nav-link" %>
          </li>
        <% end %>

        <li class="nav-item dropdown mt-10px mt-md-0">
          <div id='open-navbar-menu' class='user-menu flex-row-sb-center' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <!-- id="navbarDropdown" -->
            <div class='bar-menu flex-row-center-center'><i class="fas fa-bars"></i></div>
            <i class="fas fa-user-circle user-logo"></i>
          </div>
          <!-- <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if !signed_in? %>
              <%= link_to "Connexion", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Inscription", new_user_registration_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Mes informations", '#', class: "dropdown-item" %>
              <%= link_to "Mes commandes", '#', class: "dropdown-item" %>
              <%= link_to "Historique", '#', class: "dropdown-item" %>
            <% end %> -->
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_menu.html.erb
<div id='navbar-menu' class='navbar-menu meal_pop_up_bg_filter hidden' >
  <div class='nav-menu'>

    <div class='nav-menu-header flex-row-start-center'>
      <% if signed_in? %>
        <div class='nav-menu-profil-picture mr-2' ></div>
        <div class='nav-menu-profil-details flex-column-sb'>
          <h4>Claire Denis</h4>
          <div class='cook-sticker flex-column-center-center'>CUISINIER</div>
        </div>
      <% else %>
        <%= link_to homepage_path, class: "" do %>
          <%= image_tag 'logo.png', class: 'navbar-logo' %>
        <% end %>
      <% end %>

      <div id='close-navbar-menu' class='nav-menu-cross'><i class="fas fa-times"></i></div>
    </div>

    <div class='nav-menu-body'>

      <% if signed_in? %>

        <%= link_to user_path(current_user) do %>
          <div class='nav-menu-item grey-medium-16'>Mon compte</div>
        <% end %>
        <%= link_to user_orders_path(current_user) do %>
          <div class='nav-menu-item grey-medium-16'>Mes commandes</div>
        <% end %>

        <div class='nav-menu-cook-area'>

          <h3 class='nav-menu-item'>Espace cuisinier</h3>
          <%= link_to cook_dashboard_orders_path do  %>
            <div class='nav-menu-item grey-medium-16'>Mes missions</div>
          <% end %>
          <div class='nav-menu-item grey-medium-16'>Mes disponibilités</div>
          <%= link_to cook_dashboard_categories_path do %>
            <div class='nav-menu-item grey-medium-16'>Mes recettes</div>
          <% end %>
          <%= link_to cook_dashboard_cook_path(current_user.cook) do %>
            <div class='nav-menu-item grey-medium-16'>Mon profil</div>
          <% end %>
        </div>

        <div class='nav-menu-item grey-medium-16'>FAQ</div>
        <%= link_to destroy_user_session_path, method: 'DELETE' do %>
          <div class='nav-menu-item grey-medium-16'>Déconnexion</div>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <div class='nav-menu-item grey-medium-16'>Connexion</div>
        <% end %>
        <%= link_to new_user_registration_path do %>
          <div class='nav-menu-item grey-medium-16'>Inscription</div>
        <% end %>
      <% end %>

    </div>

  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class='searchbar-bg yellow-bg flex-row-center-center'>
  <div class="searchbar-card white-bg flex-row-sb">

    <%= simple_form_for :search, url: cooks_path, method: 'get',
      wrapper: :inline_form,
      html: { class: "form-inline searchbar-form flex-row-sb" },
      wrapper_mappings: {
        boolean: :inline_boolean
      } do |f| %>

      <div class='searchbar-item flex-column-sb'>
        <h3 class='font-size-18'>Quand ?</h3>
        <div class='flex-row-start-center'>
          <div class='mr-2'><i class="far fa-calendar-alt searchbar-text"></i></div>
          <%= f.input :date, input_html: { placeholder: 'Choisis ta date', class: "searchbar-field searchbar-text" } %>
        </div>
      </div>

      <div class='searchbar-item flex-column-sb'>
        <h3 class='font-size-18'>Où ?</h3>
        <div class='flex-row-start-center'>
          <div class='mr-2'><i class="fas fa-map-marker-alt searchbar-text"></i></i></div>
          <%= f.input :location, input_html: { placeholder: 'Entre ton adresse', class: "searchbar-field searchbar-text" } %>
        </div>
      </div>

      <%= f.button :submit, value: 'Valider' ,class: "red-btn" %>
    <% end %>

  </div>
</div>