config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home', as: 'homepage'

  resources :cooks, only: :index

  namespace :cook_dashboard do
    resources :cooks, only: %i[show update]
    resources :orders, only: %i[index update] do
      patch 'accept'
      patch 'decline'
      patch 'cancel'
    end
    resources :categories, except: %i[show edit]
  end

  resources :meals, only: %i[update new create destroy] do
    get 'details'
  end

  resources :baskets, only: :show do
    get 'create', on: :collection
    get 'total_price', on: :member
    resources :orders, only: :create
    resources :cooks, only: :show
    resources :meals, only: [] do
      get 'presence_checking'
    end
  end

  resources :users, only: :show do
    resources :orders, only: :index do
      patch 'accept'
    end
    patch 'update_details'
  end

  resources :basket_suborders, only: %i[create update destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :cook
  has_many   :meals

  include ChildrenRanksConcern
end

app/controllers/cook_dashboard/categories_controller.rb
class CookDashboard::CategoriesController < ApplicationController
  include UpdateRanksConcern

  def index
    @user = current_user
    @cook = @user.cook
    @categories = @cook.categories.order(:rank)
  end

  def new
    @category = Category.new
    @cook = current_user.cook
  end

  def create
    category = Category.new
    category.rank = current_user.cook.categories.count + 1
    save_category_based_on_params(category)
  end

  def update
    category = Category.find(params[:id])
    save_category_based_on_params(category)
  end

  def destroy
    category = Category.find(params[:id])
    cook = current_user.cook
    update_ranks(category, # selected_element
                 cook.categories.count, # new_rank
                 category.rank) # old_rank
    category.destroy
    redirect_to cook_dashboard_categories_path
  end

  private

  def save_category_based_on_params(category)
    cook = current_user.cook
    required_params = params.require(:category).permit(:name, :rank)
    category.update(name: required_params[:name], cook: cook)
    update_ranks(category, # selected_element
                 required_params[:rank].to_i, # new_rank
                 category.rank) # old_rank
    redirect_to cook_dashboard_categories_path
  end
end

app/controllers/cook_dashboard/cooks_controller.rb
class CookDashboard::CooksController < ApplicationController
  def show
    @user = current_user
    @cook = current_user.cook
  end

  def update
    cook_details = params.require(:cook).permit(:first_name, :last_name, :description)
    current_user.cook.update(cook_details)
    redirect_back(fallback_location: homepage_path)
  end
end

app/controllers/cook_dashboard/orders_controller.rb
class CookDashboard::OrdersController < ApplicationController
  def index
    @user = current_user
    @order = Order.last
  end

  def update
    # something
    update_customer_validation(nil)
  end

  def accept
    update_cook_validation(true)
  end

  def decline
    update_cook_validation(false)
  end

  def cancel
    update_cook_validation(nil)
  end

  private

  def update_cook_validation(new_status)
    @order = Order.find(params[:order_id])
    @order.cook_validation = new_status
    @order.save
    redirect_to cook_dashboard_orders_path
  end

  def update_customer_validation(new_status)
    @order = Order.find(params[:order_id])
    @order.customer_validation = new_status
    @order.save
    redirect_to cook_dashboard_orders_path
  end
end

app/helpers/cook_dashboard/categories_helper.rb
module CookDashboard::CategoriesHelper
end

app/helpers/cook_dashboard/cooks_helper.rb
module CookDashboard::CooksHelper
end

app/helpers/cook_dashboard/orders_helper.rb
module CookDashboard::OrdersHelper
end

app/views/cook_dashboard/categories/index.html.erb
<div class='yellow-banner'>
  <div class='dashboard-container banner-title'>
    <div class='w-100 flex-row-sb-end'>
      <h2>Mes recettes</h2>
      <div class='flex-column-sb-end mb-1'>
        <%= link_to new_meal_path do %>
          <div class='flex-row-start-center pointer white-font'>
            <i class="far fa-plus-square"></i>
            <p class='add-element-link'>Ajouter une nouvelle recette</p>
          </div>
        <% end %>
        <%= link_to new_cook_dashboard_category_path do %>
          <div class='flex-row-start-center pointer white-font mt-2'>
            <i class="far fa-plus-square"></i>
            <p class='add-element-link'>Ajouter une nouvelle catégorie</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class='dashboard-container page-lifted'>

  <!-- CATEGORY CARD -->

  <% @categories.each do |category| %>

    <div class='dashboard-card mt-0'>

      <div class='meal-dashboard-card'>
        <div class='dashboard-card-header category-card flex-row-sb-center'>
          <h3 class='dashboard-card-title white-font'><%= category.rank %>. <%= category.name %></h3>
          <div class='white-font flex-row-sb-center'>
            <div class='display-card-body pointer'><i class="fas fa-pen"></i></div>
            <div class='hide-card-body pointer hidden'><i class="fas fa-chevron-up"></i></div>
          </div>
        </div>
        <div class='dashboard-card-body hidden basket-form <%= 'border-bottom' unless category.meals.empty? %>'>
          <div class=''>
            <%= render partial: 'shared/category_form', locals: {category: category,
                                                                 category_ranks: @cook.children_ranks_array(params[:action]),
                                                                 url: cook_dashboard_category_path(category),
                                                                 method: 'PATCH',
                                                                 button: 'Enregistrer les modifications'} %>
            <% if category.meals.where(deleted: [nil, false]).empty? %>
              <%= link_to cook_dashboard_category_path(category), method: 'DELETE' do %>
                <p class='orange-14 pointer underline mt-3'>Supprimer la catégorie</p>
              <% end %>
            <% else %>
              <p class='orange-14 mt-3'>Vous ne pouvez supprimer une catégorie seulement si elle est vide.</p>
            <% end %>

          </div>
        </div>
      </div>

      <!-- MEAL CARD -->

      <% category.meals.order(:rank).where(deleted: [nil, false]).each do |meal| %>

        <div class='meal-dashboard-card'>
          <div class='meal-dashboard-card-header flex-row-sb-center <%= 'no-border-top' if meal.id == category.meals.first.id %>'>
            <h3 class=''><%= meal.rank %>. <%= meal.name %></h3>
            <div class='display-card-body pointer'><i class="fas fa-chevron-down"></i></div>
            <div class='hide-card-body pointer hidden'><i class="fas fa-chevron-up"></i></div>
          </div>

          <div class='pt-0 dashboard-card-body basket-form hidden'>
            <!-- MEAL FORM -->
            <%= render partial: 'shared/meal_form', locals: {meal: meal,
                                                             ingredient_ranks: meal.children_ranks_array,
                                                             meal_ranks: category.children_ranks_array(params[:action]),
                                                             categories: @categories,
                                                             url: meal_path(meal),
                                                             method: 'PATCH',
                                                             button: 'Enregistrer les modifications'} %>
            <%= link_to meal_path(meal), method: 'DELETE' do %>
              <p class='orange-14 pointer underline mt-3'>Supprimer la recette</p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<%= javascript_pack_tag 'ingredientsRanking', 'categoryIndex/index'%>

app/views/cook_dashboard/categories/new.html.erb
<div class='yellow-banner'>
  <div class='dashboard-container banner-title'>
    <h2>Ajouter une nouvelle recette</h2>
  </div>
</div>

<div class='dashboard-container page-lifted'>
  <div class='dashboard-card mt-0'>
    <div class='dashboard-card-header category-card flex-row-start-center'>
      <h3 class='dashboard-card-title white-font'>Détails</h3>
    </div>
    <div class='dashboard-card-body basket-form'>
      <div class=''>
        <%= render partial: 'shared/category_form', locals: {category: @category,
                                                             category_ranks: @cook.children_ranks_array(params[:action]),
                                                             url: cook_dashboard_categories_path,
                                                             method: 'POST',
                                                             button: 'Ajouter la catégorie'} %>
      </div>
    </div>
  </div>
</div>